services:
  - type: web
    name: llm-tg-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free